--------------------------------------------------------
--  파일이 생성됨 - 화요일-7월-05-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HTA_BOOKS
--------------------------------------------------------

  CREATE TABLE "SEMI"."HTA_BOOKS" 
   (	"BOOK_NO" NUMBER(6,0), 
	"CATEGORY_NO" NUMBER(6,0), 
	"BOOK_TITLE" VARCHAR2(255 BYTE), 
	"BOOK_AUTHOR" VARCHAR2(255 BYTE), 
	"BOOK_PUBLISHER" VARCHAR2(255 BYTE), 
	"BOOK_DESCRIPTION" CLOB, 
	"BOOK_PRICE" NUMBER(8,0), 
	"BOOK_DISCOUNT_PRICE" NUMBER(8,0), 
	"BOOK_ON_SELL" CHAR(1 BYTE) DEFAULT 'Y', 
	"BOOK_STOCK" NUMBER(6,0), 
	"BOOK_CREATED_DATE" DATE DEFAULT SYSDATE, 
	"BOOK_UPDATED_DATE" DATE, 
	"BOOK_DELETED" CHAR(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("BOOK_DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table HTA_USERS
--------------------------------------------------------

  CREATE TABLE "SEMI"."HTA_USERS" 
   (	"USER_NO" NUMBER(6,0), 
	"USER_EMAIL" VARCHAR2(255 BYTE), 
	"USER_PASSWORD" VARCHAR2(255 BYTE), 
	"USER_NAME" VARCHAR2(255 BYTE), 
	"USER_TEL" VARCHAR2(255 BYTE), 
	"USER_DELETED" CHAR(1 BYTE) DEFAULT 'N', 
	"USER_CREATED_DATE" DATE DEFAULT SYSDATE, 
	"USER_UPDATED_DATE" DATE, 
	"USER_DEFAULT_AD_NO" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HTA_BOOK_CATEGORIES
--------------------------------------------------------

  CREATE TABLE "SEMI"."HTA_BOOK_CATEGORIES" 
   (	"CATEGORY_NAME" VARCHAR2(255 BYTE), 
	"CATEGORY_NO" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HTA_BOOKS_NO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMI"."HTA_BOOKS_NO_PK" ON "SEMI"."HTA_BOOKS" ("BOOK_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HTA_USER_NO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMI"."HTA_USER_NO_PK" ON "SEMI"."HTA_USERS" ("USER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008691
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMI"."SYS_C008691" ON "SEMI"."HTA_USERS" ("USER_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008643
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMI"."SYS_C008643" ON "SEMI"."HTA_BOOK_CATEGORIES" ("CATEGORY_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table HTA_BOOKS
--------------------------------------------------------

  ALTER TABLE "SEMI"."HTA_BOOKS" MODIFY ("BOOK_NO" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."HTA_BOOKS" MODIFY ("CATEGORY_NO" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."HTA_BOOKS" MODIFY ("BOOK_TITLE" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."HTA_BOOKS" MODIFY ("BOOK_AUTHOR" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."HTA_BOOKS" MODIFY ("BOOK_PUBLISHER" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."HTA_BOOKS" ADD CONSTRAINT "HTA_BOOKS_NO_PK" PRIMARY KEY ("BOOK_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SEMI"."HTA_BOOKS" MODIFY ("BOOK_STOCK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HTA_USERS
--------------------------------------------------------

  ALTER TABLE "SEMI"."HTA_USERS" MODIFY ("USER_NO" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."HTA_USERS" MODIFY ("USER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."HTA_USERS" MODIFY ("USER_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."HTA_USERS" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."HTA_USERS" MODIFY ("USER_TEL" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."HTA_USERS" ADD CONSTRAINT "HTA_USER_NO_PK" PRIMARY KEY ("USER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SEMI"."HTA_USERS" ADD UNIQUE ("USER_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HTA_BOOK_CATEGORIES
--------------------------------------------------------

  ALTER TABLE "SEMI"."HTA_BOOK_CATEGORIES" MODIFY ("CATEGORY_NAME" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."HTA_BOOK_CATEGORIES" MODIFY ("CATEGORY_NO" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."HTA_BOOK_CATEGORIES" ADD PRIMARY KEY ("CATEGORY_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HTA_BOOKS
--------------------------------------------------------

  ALTER TABLE "SEMI"."HTA_BOOKS" ADD FOREIGN KEY ("CATEGORY_NO")
	  REFERENCES "SEMI"."HTA_BOOK_CATEGORIES" ("CATEGORY_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HTA_USERS
--------------------------------------------------------

  ALTER TABLE "SEMI"."HTA_USERS" ADD CONSTRAINT "FK_DEFAULT_AD_NO" FOREIGN KEY ("USER_DEFAULT_AD_NO")
	  REFERENCES "SEMI"."HTA_USER_ADDRESSES" ("ADDRESS_NO") ON DELETE CASCADE ENABLE;
